### ISSUE TITLE
Unable to open file in go to definition feature

### ISSUE THREAD

**Issue by miguelcaravantes** [graphql/vscode-graphql#129]
## Actual Behavior
when i try to go to definition visual studio tries to open the file related, but despite the path is correct. there are two backslash "\\" before c:\ and visual studio is unable to open that file.
![image](https://user-images.githubusercontent.com/17279582/64043104-194bb380-cb29-11e9-9dec-3aa7404f334a.png)

## Expected Behavior
when someone click in go to definition or push F12 key, visual studio should open the file related.

## Steps to Reproduce the Problem Or Description
select a custom graphql type.
click in go to definition
visual studio tries to open the file
get a exception in windows 10

## Specifications

  - GraphQL for VSCode Extension Version: 0.2.1
  - VSCode Version: 1.37.1
  - OS Name: Windows
  - OS Version: 10

**Comment by damiangreen** [comment]
Ours takes us to an ambient type definition for graphql
````
declare module '*.graphql' {
  import { DocumentNode } from 'graphql'

  const value: DocumentNode
  export = value
}
```

**Comment by acao** [comment]
This should be fixed now
