### ISSUE TITLE
Support autocomplete with comments

### ISSUE THREAD

**Issue by gogoyqj** [graphql/vscode-graphql#140]
just like pic bellow, if supported, life becomes easier, lol

![image](https://user-images.githubusercontent.com/1776278/68443472-e6036000-020e-11ea-8f3d-449f8eb46faf.png)

**Comment by acao** [comment]
ooh this would be very nice! great idea

**Comment by gogoyqj** [comment]
@achao any progress?

**Comment by acao** [comment]
@gogoyqj this already works, the description expands on hover!
