### ISSUE TITLE
Got this warning in VS Code - GraphQL Extension causes high cpu load

### ISSUE THREAD

**Issue by faddah** [graphql/vscode-graphql#234]
- Issue Type: `Performance`
- Extension Name: `vscode-graphql`
- Extension Version: `0.3.10`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.49.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/faddah/GraphQL.vscode-graphql-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

Got this warning when I updated to the August 2020 v1.49 of XCode. It says this extension slowed down all other extensions loading. Though you'd want to know.

**Comment by xiaoyu-tamu** [comment]
Same here, 

After upgrade to V3, the cpu usage is high after after run some code generation. I have to manually kill vscode processes.

Where can I find older releases?

**Comment by raikusy** [comment]
Any update on this?

**Comment by Noorullah-Ahmadzai** [comment]
I'm here to confirm
