### ISSUE TITLE
CPU Usage is high after V3

### ISSUE THREAD

**Issue by xiaoyu-tamu** [graphql/vscode-graphql#235]
The processes monitor is sort by %CPU usage after run code generation.

V0.2.38
![image](https://user-images.githubusercontent.com/33362998/94950617-878b4400-04a8-11eb-887c-f1e9d19dd074.png)

V0.3+
![image](https://user-images.githubusercontent.com/33362998/94950833-dd5fec00-04a8-11eb-8db0-093307daceb3.png)

**Comment by acao** [comment]
`0.2.38` did not have a way to cache files via the code helper, so maybe thats why?
