### ISSUE TITLE
Not working with self signed certificates

### ISSUE THREAD

**Issue by solomon23** [graphql/vscode-graphql#241]
## Actual Behavior

My graphql endpoint uses ssl with a self signed certificate which is failing

## Expected Behavior

It should work be able to connect to the endpoint or at least let us set a flag to allow insecure connections `NODE_TLS_REJECT_UNAUTHORIZED`

## Steps to Reproduce the Problem Or Description

Point your yaml config to a server with a self signed cert

```
schema: https://xxx/graphql
documents: '**/*.{graphql,js,ts,jsx,tsx}'
extensions:
  endpoints:
    default:
      url: https://xxx/graphql
```

## Specifications

  - GraphQL for VSCode Extension Version: 
  - VSCode Version:
  - OS Name:
  - OS Version:

## Logs Of TS Server || GraphQL Language Service

10/14/2020, 10:16:18 AM [1] (pid: 44156) graphql-language-service-usage-logs: FetchError: request to xxx failed, reason: self signed certificate

(node:44156) UnhandledPromiseRejectionWarning: FetchError: request to https://xxx/graphql failed, reason: self signed certificate
    at ClientRequest.<anonymous> (xxx/.vscode/extensions/graphql.vscode-graphql-0.3.10/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:44156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10/14/2020, 10:18:36 AM [3] (pid: 44156) graphql-language-service-usage-logs: updating graphql config

**Comment by FreekVR** [comment]
+1 for this, I additionally added NODE_TLS_REJECT_UNAUTHORIZED=0 to my `.env` file but alas, no luck :(
