### ISSUE TITLE
Suggest / autocomplete arguments on fields

### ISSUE THREAD

**Issue by janbaykara** [graphql/vscode-graphql#25]
It'd be cool if arguments could be suggested, as they are with graphiql.

#### vscode-graphql:
<img width="454" alt="screen shot 2018-06-19 at 13 25 48" src="https://user-images.githubusercontent.com/237556/41597154-8ab6d238-73c4-11e8-8a47-72a74024ca01.png">

#### graphiql:
<img width="331" alt="screen shot 2018-06-19 at 13 27 47" src="https://user-images.githubusercontent.com/237556/41597188-985f159e-73c4-11e8-82e8-f6f73ceccd22.png">

**Comment by divyenduz** [comment]
This should work by pressing `ctrl+space`
