### ISSUE TITLE
File handling on Windows seems broken (v0.3.11)

### ISSUE THREAD

**Issue by lanwin** [graphql/vscode-graphql#254]
## Actual Behavior

It seems the windows file handling is broken. Ive tried it on two different systems with to different projects and see a lot of UnhandledPromiseRejectionWarning on both of them.

## Expected Behavior

Files should be found an Windows too.

## Steps to Reproduce the Problem Or Description

My graphql.config.yaml looks like that and works fine with graphql generator.
```
schema: ./src/generated/graphql_schema.graphql
documents: ./src/*.gql
extensions:
  languageService:
    useSchemaFileDefinitions: true
```

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.11
  - VSCode Version: 1.51.1
  - OS Name: Windows 10
  - OS Version: 10.0.19041 Build 19041

## Logs Of TS Server || GraphQL Language Service

Initial:
```
undefined
(node:13428) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/c%3A/Users/test/test/graphql.config.yaml'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at c:\Users\test\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\graphql-language-service-server\dist\MessageProcessor.js:353:35
    at Array.map (<anonymous>)
    at MessageProcessor.handleWatchedFilesChangedNotification (c:\Users\test\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\graphql-language-service-server\dist\MessageProcessor.js:342:43)
    at c:\Users\test\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\graphql-language-service-server\dist\startServer.js:164:122
    at handleNotification (c:\Users\Steve Wagner\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\vscode-jsonrpc\lib\main.js:502:43)
    at processMessageQueue (c:\Users\Steve Wagner\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\vscode-jsonrpc\lib\main.js:273:17)
(node:13428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside 
```of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
```
Open and save a gql file
```
undefined
(node:13428) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/c%3A/Users/test/test/src/query.gql'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at c:\Users\test\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\graphql-language-service-server\dist\MessageProcessor.js:353:35
    at Array.map (<anonymous>)
    at MessageProcessor.handleWatchedFilesChangedNotification (c:\Users\test\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\graphql-language-service-server\dist\MessageProcessor.js:342:43)
    at c:\Users\test\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\graphql-language-service-server\dist\startServer.js:164:122
    at handleNotification (c:\Users\test\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\vscode-jsonrpc\lib\main.js:502:43)
    at processMessageQueue (c:\Users\test\.vscode\extensions\graphql.vscode-graphql-0.3.11\node_modules\vscode-jsonrpc\lib\main.js:273:17)
(node:13428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```

**Comment by lanwin** [comment]
I found the root cause in graphql-languageserver and opened a pullrequest to fix it https://github.com/graphql/graphiql/pull/1715

**Comment by Odonno** [comment]
I still have this issue. Any help?

**Comment by jer-sen** [comment]
Still an issue with last version `0.3.40`. I get for example:

- Unable to open 'queries.gql': Unable to resolve resource c:/dev/path/to/focument/file/queries.gql.
- Unable to open 'queries.gql': Unable to resolve resource c:%5Cdev%5Cpath%5Cto%5Cschema%5Cfile%5Cqueries.gql.

**Comment by Cellule** [comment]
@acao I did port the fix from https://github.com/graphql/graphiql/pull/2214 to my local `%userprofile%\.vscode\extensions\graphql.vscode-graphql-0.3.50\out\server\server.js` and it's been working great so far.
0.3.50 doesn't seem to have to fix yet however

**Comment by acao** [comment]
It seems your change is present in the lockfile though?

https://github.com/graphql/graphiql/blob/main/packages/graphql-language-service-server/CHANGELOG.md#2714

https://github.com/graphql/vscode-graphql/blob/22d6fe032aee42db722cf3773e595f060446e46b/package-lock.json#L2527

strange... @orta noting a potential pipeline bug here

**Comment by Cellule** [comment]
I'm not sure how the pre-release channel works, but from my point of view 0.3.50 was released 2 months ago (which I used to test my original fix)
![image](https://user-images.githubusercontent.com/4157103/157509023-96486023-4810-49c2-9308-4fd59ceb8641.png)

**Comment by acao** [comment]
Huh! Well hopefully someone can take a look at the publishing pipeline soon. I must have misunderstood what happened in the logs. I am about to undergo surgery so it will take me a while to get a chance to try this again

**Comment by frederikhors** [comment]
Same here with freshly installed 0.3.50 using the "Switch to Pre-Release" button in VSCode on Windows 10. Any fix?

**Comment by Cellule** [comment]
I believe the PR https://github.com/graphql/vscode-graphql/pull/447 indeed tried to deploy 0.3.50
however, it seems 0.3.50 was already on the store since 2 months ago even though the version in package.json was still 0.3.49
so I believe we should retrigger the release with same changelog for 0.3.51 (not sure how that works :( )

**Comment by acao** [comment]
it was a bug from when I tried to get vscode pre-releases working on each merge, I think I can get it to publish in a single commit. the openvsx token with oracle is expired but I should be able to publish to vsc marketplace

**Comment by acao** [comment]
`0.3.52` contains this fix, enjoy!

**Comment by Cellule** [comment]
Awesome! just tested with 0.3.52 and it's all good
Thanks
