### ISSUE TITLE
env vars don't not work properly

### ISSUE THREAD

**Issue by mdreizin** [graphql/vscode-graphql#257]
## Actual Behavior

Env vars does not work properly even if they are valid.

## Expected Behavior

Should be working fine.

## Steps to Reproduce the Problem Or Description

1. Create `.env` file
2. Set `GRAPHQL_TOKEN=xxx` with a valid value
3. Create `graphql.config.js` with the content:

```js
console.log('GRAPHQL_TOKEN', process.env.GRAPHQL_TOKEN) // `GRAPHQL_TOKEN` is set and value is `xxx`

module.exports = {
  projects: {
    'default': {
      name: "GraphQL API",
      schema: [
        "./graphql/schema.graphql",
        "./graphql/**/*.graphql"
      ],
      extensions: {
        endpoints: {
          dev: {
            url: "http://localhost:8080/graphql",
            headers: {
              Authorization: `Bearer ${process.env.GRAPHQL_TOKEN}`
            },
            introspect: false
          }
        }
      }
    }
  }
}
```

4. Call any queries/mutations:

```
ServerParseError: Unexpected token U in JSON at position 0
```

If I set the token value manually then **it will work**:

```diff
-Authorization: `Bearer ${process.env.GRAPHQL_TOKEN}`
+Authorization: `Bearer xxx`
```

The following config doesn't work as well:

```diff
-Authorization: `Bearer ${process.env.GRAPHQL_TOKEN}`
+Authorization: "Bearer ${GRAPHQL_TOKEN}"
```

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.12
  - VSCode Version: 1.51.1
  - OS Name: macOS Big Sur
  - OS Version: 11.0.1

## Logs Of TS Server || GraphQL Language Service

```
GRAPHQL_TOKEN xxx
11/20/2020, 4:27:41 PM [4] (pid: 63777) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didChange","projectName":"default","fileName":"file:///<redacted>/graphql.config.js"}
11/20/2020, 4:28:37 PM [4] (pid: 63777) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///<redacted>/graphql/scratches/scratch.graphql"}

undefined
NetworkHelper: operation: query
NetworkHelper: endpoint: http://localhost:8080/graphql
```

**Comment by aylton-almeida** [comment]
Is there any update on this? I've been trying to do this with a project and it keeps throwing me a similar Error message

**Comment by jkcorrea** [comment]
@mdreizin @aylton-almeida this was bugging me too, submitted a fix in #267 but if you want a temp fix you can patch it:

open the installed extension's `extension.js` file (somewhere like `~/.vscode/extensions/graphql.vscode-graphql-0.3.13/out/extension.js` and add this patch around line 30 (don't think it really matters where, as long as it's in that fn):

```js
if (vscode_1.workspace.workspaceFolders) {
  process.chdir(vscode_1.workspace.workspaceFolders[0].uri.fsPath);
}
```

**Comment by mdreizin** [comment]
@jkcorrea Cool! Thanks!

**Comment by acao** [comment]
the solution is to import dotenv in your .ts or .js config file!
