### ISSUE TITLE
Clicking `Execute Query` works but also creates a burst of authentication failures, then one every 10 seconds.

### ISSUE THREAD

**Issue by jifalops** [graphql/vscode-graphql#258]
## Actual Behavior
The authentication is correct and works when I click e.g. `execute Query` in the editor, but a background processes is hitting the server every ten seconds and causing authentication failures. It appears to start happening when I click to run an operation. Disabling this plugin stops the errors.

I'm using Bearer tokens to authenticate but end up getting blocked because of all the failed background attempts.

**.graphqlrc.js**
```
const URL = '...'
const API_TOKEN = '...'

module.exports = {
  projects: {
    myProject: {
      schema: "graphql/schema.graphql",
      documents: "graphql/**/*.gql",
      extensions: {
        endpoints: {
          remote: {
            url: URL,
            headers: {
              Authorization: `Bearer ${API_TOKEN}`
            },
          }
        }
      },
    }
  }
}
```
![image](https://user-images.githubusercontent.com/826613/99867871-85319600-2b8b-11eb-9865-33f083debd3b.png)

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.12
  - VSCode Version: 1.51.1
  - OS Name: Ubuntu
  - OS Version: 20.04

**Comment by jifalops** [comment]
That is, everything is fine in the IDE with those settings (until I get blocked by the server). Digging into it I've found that this plugin is causing authentication failures, which is why I'm getting blocked.

**Comment by acao** [comment]
We no longer support query execution
