### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Walterpina** [graphql/vscode-graphql#259]
- Issue Type: `Bug`
- Extension Name: `vscode-graphql`
- Extension Version: `0.3.12`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by divyenduz** [comment]
@Walterpina Thank you for raising this issue. You missed pasting the clipboard content and without this we can't make progress on this issue, please do that or we will have to close this issue soon :)

**Comment by tanyapowell** [comment]
I'm also having an issue with version `1.51.1`

---
- Issue Type: `Bug`
- Extension Name: `vscode-graphql`
- Extension Version: `0.3.12`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.51.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 15743,
		"activateCallTime": 5,
		"activateResolvedTime": 72,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GraphQL.vscode-graphql",
				"_lower": "graphql.vscode-graphql"
			},
			"activationEvent": "workspaceContainsTimeout:**/.graphqlrc,**/.graphqlrc.{json,yaml,yml,js},**/graphql.config.{json,yaml,yml,js}"
		}
	},
	"runtimeErrors": []
}
```

**Comment by vishalrao8** [comment]
- Issue Type: `Bug`
- Extension Name: `vscode-graphql`
- Extension Version: `0.3.13`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.52.1`

This extension is causing performance issues in VSCode when used in my Flutter/Dart project.

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8898,
		"activateCallTime": 6,
		"activateResolvedTime": 6,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GraphQL.vscode-graphql",
				"_lower": "graphql.vscode-graphql"
			},
			"activationEvent": "workspaceContainsTimeout:**/.graphqlrc,**/.graphqlrc.{json,yaml,yml,js},**/graphql.config.{json,yaml,yml,js}"
		}
	},
	"runtimeErrors": []
}
```
