### ISSUE TITLE
Add status indicator to status bar

### ISSUE THREAD

**Issue by peterschussheim** [graphql/vscode-graphql#27]
It would be very useful to have some type of indicator (spinner, whatever) in the status bar that updates whenever the graphql lang server is working.  

While the implementation is not identical, here is an example from [flow-vs-code ext](https://github.com/flowtype/flow-for-vscode/blob/77033ead97fe14fb0b8fc00732518cd94f644b50/lib/flowStatus.js) that provides this feature.

### Example showing another ext with this feature:

![flow-vscode](https://github.com/flowtype/flow-for-vscode/raw/master/readme/flow-main.gif)

**Comment by divyenduz** [comment]
Related issue: https://github.com/graphql/graphql-language-service/issues/230
