### ISSUE TITLE
Error using Apollo Client rest directive 

### ISSUE THREAD

**Issue by HosseinAgha** [graphql/vscode-graphql#272]
## Actual Behavior
I get the `Unknown directive "@rest". GraphQL: Validation` error but I don't get the same error when I run apollo-codegen.

## Expected Behavior
The predefined [apollo client directives](https://www.apollographql.com/docs/devtools/apollo-config/#clientclientonlydirectives-clientclientschemadirectives) should be added by default.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.13
  - VSCode Version: 1.52.1

## Logs Of TS Server || GraphQL Language Service
I don't see any errors in the `GraphQL Language Service` output.

**Comment by vladev** [comment]
I'm also struggling with this and even doing something like this has no effect:
```
# graphql.config.ts
import type { IGraphQLProject } from 'graphql-config'

const apolloRestSchema = require.resolve('apollo-link-rest/schema.graphql')

const config: IGraphQLProject = {
  schema: ['http://localhost:4000/graphql', 'lib/rest.graphql'],
  documents: 'graphql/*.graphql',
  include: [apolloRestSchema],
```

**Comment by acao** [comment]
this should help!

https://github.com/graphql/vscode-graphql/issues/55
