### ISSUE TITLE
Get variable value from user is not working for complex type

### ISSUE THREAD

**Issue by PrasadJayakumar** [graphql/vscode-graphql#275]
## Actual Behavior
User input dialog works for scalar type.  If I pass complex values like **{Id: "5621" targetVolume: "10"}**, then I get error
**Expected type ComplexInput be an object.**

mutation($Input: [ComplexInput]) {
  save(input: $Input) {
   id
  }
}

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.13
  - VSCode Version: 1.52.1
  - OS Name: Windows
  - OS Version:

## Logs Of TS Server || GraphQL Language Service

"    at /app/node_modules/graphql/execution/values.js:114:15",
            "    at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:83:7)",
            "    at coerceInputValue (/app/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
            "    at _loop (/app/node_modules/graphql/execution/values.js:107:69)",
            "    at coerceVariableValues (/app/node_modules/graphql/execution/values.js:119:16)",
            "    at getVariableValues (/app/node_modules/graphql/execution/values.js:48:19)",
            "    at buildExecutionContext (/app/node_modules/graphql/execution/execute.js:184:61)",
            "    at executeImpl (/app/node_modules/graphql/execution/execute.js:89:20)",
            "    at Object.execute (/app/node_modules/graphql/execution/execute.js:64:35)",

**Comment by acao** [comment]
We no longer support query execution in this extension, but if we re-introduce it, we will provide a different UI
