### ISSUE TITLE
 highlight an embedded graphql string for .svelte files

### ISSUE THREAD

**Issue by lukasIO** [graphql/vscode-graphql#292]
## Actual Behavior
![grafik](https://user-images.githubusercontent.com/12997837/111303885-5ae17800-8655-11eb-9f22-7c8a447e7437.png)

## Expected Behavior
![grafik](https://user-images.githubusercontent.com/12997837/111303931-659c0d00-8655-11eb-88cb-9fb6c42d9ceb.png)

## Steps to Reproduce the Problem Or Description
install the most recent plugin version, type 
```js
const myQuery = (lang) => `#graphql
  query {
    something
  }
`
```
in a .svelte file.

My naive guess is, that `source.svelte` is still missing here:
 https://github.com/graphql/vscode-graphql/blob/33a5edc32e7483602b2e95eee09184073cd28abe/package.json#L67-L73
while it is already added here:
https://github.com/graphql/vscode-graphql/blob/52e3b52636d56c4e113818f2935b605733776739/grammars/graphql.js.json#L2

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.15
  - VSCode Version: 1.54
  - OS Name: Ubuntu
  - OS Version:  20.04

**Comment by acao** [comment]
@lukasIO can you open a PR? thanks!

**Comment by asmimo** [comment]
I am not getting auto completion inside svelte files(nor vue too). Do I need to configure it or is it not available yet?

**Comment by acao** [comment]
So, what lukas suggested here would introduce highlighting. To introduce completion for svelte files would be another effort entirely, but is on the radar and will eventually be on a roadmap

**Comment by Shinigami92** [comment]
@acao Could you link me the issue to track the progress of `completion support for vue`?
I need this also
