### ISSUE TITLE
useSchemaFileDefinitions doesn't seem to work anymore

### ISSUE THREAD

**Issue by Sytten** [graphql/vscode-graphql#317]
## Actual Behavior
When enabling `useSchemaFileDefinitions`, it doesn't go in the code definitions.

## Expected Behavior
When `useSchemaFileDefinitions` is enabled, go to definition opens the source code.

## Steps to Reproduce the Problem Or Description
1. Create a monorepo with yarn
2. Create a a package in packages for the api
3. Create a basic apollo schema-first schema
4. Use codegen to generate the schema
5. Point the extension to both the schema and the document
6. Control-click on one item and you get redirected to the schema

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.16
  - VSCode Version: 1.58.2
  - OS Name: Mac
  - OS Version: 10.14

**Comment by acao** [comment]
I changed this setting. now SDL works by default, and the remote schema cacheing needs to be enabled
