### ISSUE TITLE
Fix: Hello, please minute of attention, https://github.com/graphql/graphiql/pull/1715 was not applied

### ISSUE THREAD

**Issue by orsenkucher** [graphql/vscode-graphql#320]
- GraphQL for VSCode Extension Version: git cloned from 558a414d29cf749dd4234ff98d19554fe769fce4 (basically latest master right now)
- VSCode Version: 1.59
- OS Name: Windows

Hello, please bump `graphql-language-service-server` dependency from `^2.5.6` -> `^2.5.7` or later
or update `.lock` files
Because, as my investigation has shown current dependency setup **does not** contain changes from https://github.com/graphql/graphiql/pull/1715

Thus I don't have `Go to Definition` navigation working, the URI of file resource to open is malformed for windows.

Steps to reproduce: 
1. clone repo
2. run `npm install`
3. look at `node_modules\graphql-language-service-server\dist\MessageProcessor.js\MessageProcessor\handleDefinitionRequest` 
and at `ln: 438` your should see
```js
return {
    uri: res.path.indexOf('file:///') === 0
        ? res.path
        : `file://${path.resolve(res.path)}`,
    range: defRange,
};
```
If you run from `Debug` -> `Extension` now, code navigation won't work on windows.
4. now delete the `yarn.lock`, `package-lock.json` and `node_modules`
5. run `npm install` again
6. look up the same file, at `ln: 440` you will see
```js
return {
    uri: res.path,
    range: defRange,
};
```
Which is now correct and everything works as expected 🥰

**Comment by orsenkucher** [comment]
Ok, so I've downloaded `.tgz` from npm `graphql-language-service-server` of version `2.5.6` and it doesn't  contain needed fix

**Comment by orsenkucher** [comment]
Published https://marketplace.visualstudio.com/items?itemName=orsenkucher.vscode-graphql
And it works on Windows 😱🤯😎🥳🤪

**Comment by ferm10n** [comment]
Creating a PR might be a good idea to get the maintainers to check this out. I'm curious why you added codemirror and change the typescript dependency though https://github.com/orsenkucher/vscode-graphql/commit/06fbd5fec23be82a5622bc1e315e564f95550f00#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by acao** [comment]
We just need a PR to update our language server to use our latest LSP release! This repo will soon be merged with graphiql repo to make this part easier. If someone wants to create a PR just to update the language server to our latest version that would be rad

**Comment by acao** [comment]
this should be released now! let me know if there are issues

**Comment by NamanShergill** [comment]
> this should be released now! let me know if there are issues

I am still having this issue, I cannot use go to definition as it just says unable to resolve reference

**Comment by acao** [comment]
Are the files that contain fragments listed in `documents`?

**Comment by NamanShergill** [comment]
> Are the files that contain fragments listed in `documents`?

Yes, VS Code says it's unable to resolve the resource and lists the exact path of the file. 
![unknown](https://user-images.githubusercontent.com/33877135/150104516-18f8a3b3-d115-4d79-b86e-ff4c3867eff5.png)

**Comment by NamanShergill** [comment]
Sorry for some of the path being drawn over as this is the only image I have as I'm not on my PC, but that's the exact path the file is in.
