### ISSUE TITLE
publish-open-vsx.yml keeps failing

### ISSUE THREAD

**Issue by mtsmfm** [graphql/vscode-graphql#328]
## Actual Behavior

https://open-vsx.org/extension/GraphQL/vscode-graphql is old

![image](https://user-images.githubusercontent.com/1796864/136323264-a06ec929-00e4-40a9-9cd9-1a051fcb8854.png)

Workflow keeps failing

https://github.com/graphql/vscode-graphql/actions/workflows/publish-open-vsx.yml

## Expected Behavior

0.3.18 is available on open vsx

**Comment by acao** [comment]
this should work now, thanks for reporting!
