### ISSUE TITLE
Unknown type "ID".

### ISSUE THREAD

**Issue by bkinsey808** [graphql/vscode-graphql#331]
## Actual Behavior
Displays: Unknown type "ID". error
![image](https://user-images.githubusercontent.com/475211/136705790-d84878ee-6fc9-4130-a14c-99637a72cfe6.png)

## Expected Behavior
No unknown type error with ID

## Steps to Reproduce the Problem Or Description
source code: https://github.com/bkinsey808/nx-next-strapi
specific file error occurs on: https://github.com/bkinsey808/nx-next-strapi/blob/main/apps/client/components/commentForm/useCreateCommentForm.tsx#L9

## Specifications

  - GraphQL for VSCode Extension Version: 
  - VSCode Version:
  - OS Name: WSL2 Ubuntu
  - OS Version: Ubuntu 20.04.3 LTS

## Logs Of TS Server || GraphQL Language Service
Debugger listening on ws://localhost:6009/d597216f-ca42-416f-a4bf-979e98f684fd
For help, see: https://nodejs.org/en/docs/inspector
10/10/2021, 6:58:56 AM [4] (pid: 2798) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
10/10/2021, 6:58:56 AM [4] (pid: 2798) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///home/bkinsey/bkinsey808/nx-next-strapi/apps/client/components/commentForm/useCreateCommentForm.tsx"}

**Comment by acao** [comment]
we depend on a bleeding edge version of graphql@16 currently so it may be that some weird things are missing. I also found in a graphql-js release that isScalarType() doesn't work with Floats temporarily.

we will move to a stable graphql-js release as soon as defer and stream is merged

**Comment by acao** [comment]
to be clear, this validation comes from `graphql-js` itself
