### ISSUE TITLE
Add support for graphql.config.ts

### ISSUE THREAD

**Issue by IanVS** [graphql/vscode-graphql#334]
## Actual Behavior

Attempting to use a typescript config file results in:

```
graphql-language-service-usage-logs: TypeScriptCompileError: Failed to compile TypeScript: Unexpected token 'export'
```

It looks like `graphql.config.ts` is supported by `graphql-config`: https://graphql-config.com/introduction#graphqlconfigts-or-graphqlrcts

## Expected Behavior

I should be able to export a config from a typescript file.

## Steps to Reproduce the Problem Or Description

Define a config using a typescript file.

## Specifications

  - GraphQL for VSCode Extension Version: 
  - VSCode Version: 1.61.2 
  - OS Name: macOS
  - OS Version: 

## Logs Of TS Server || GraphQL Language Service
```
10/26/2021, 2:50:12 PM [4] (pid: 8601) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
10/26/2021, 2:50:14 PM [1] (pid: 8601) graphql-language-service-usage-logs: TypeScriptCompileError: Failed to compile TypeScript: Unexpected token 'export'
10/26/2021, 2:50:14 PM [1] (pid: 8601) graphql-language-service-usage-logs: TypeScriptCompileError: Failed to compile TypeScript: Unexpected token 'export'
10/26/2021, 2:50:14 PM [1] (pid: 8601) graphql-language-service-usage-logs: TypeScriptCompileError: Failed to compile TypeScript: Unexpected token 'export'
```

**Comment by acao** [comment]
Woah! last I updated this there wasn't support, but I introduced a PR for TS and TOML support so maybe they merged it, cool!

**Comment by acao** [comment]
this was added in the latest release, but there are other issues which may cause editor features to not load.

**Comment by sandervspl** [comment]
I am still getting this error when trying to use a .ts config with version 4.1.0

```ts
import type { IGraphQLConfig } from 'graphql-config';

const config: IGraphQLConfig = {
  schemaPath: './schema.graphql',
  documents: ['./src/**/*.graphql'],
  extensions: {
    endpoints: {
      default: {
        url: `https://graphql.contentful.com/content/v1/spaces/${process.env.NEXT_PUBLIC_CF_SPACE_ID}`,
        headers: { Authorization: `Bearer ${process.env.NEXT_PUBLIC_CF_DELIVERY_ACCESS_TOKEN}` },
      },
    },
  },
};

export default config;
```

**Comment by luisgregson** [comment]
> this was added in the latest release, but there are other issues which may cause editor features to not load.

Can you advise what the other issues are? I'm still seeing "ConfigNotFoundError2: GraphQL Config file is not available in the provided config directory", but i'm not sure what to check next
