### ISSUE TITLE
Inline fragment(s) not working

### ISSUE THREAD

**Issue by pruss** [graphql/vscode-graphql#341]
## Actual Behavior
Having segment which should return different properties depending on the type. Instead of return valid data it just returns null.
As query is working with different other ide it's not a problem with the query.

## Expected Behavior
Inline fragments returns valid data
Result:
```
{
  "data": {
    "content": {
      "content": {
        "id": "1168",
        "locale": "de-DE",
        "version": "6",
        "options": [
          {
            "id": "3198",
            "hexCode": "#c0c0c0",
            "value": "silber"
          },
          {
            "id": "3188",
            "value": "Purple Zuhause"
          },
          {
            "id": "7468",
            "value": "1"
          },
          {
            "id": "5238",
            "value": "Apple"
          }
        ]
      }
    }
  }
}
```
## Steps to Reproduce the Problem Or Description
```
query getDTAttribute($Id: String! = "1168") {
  content {
    content(id: $Id) {
      ...Attribute
    }
  }
}
fragment Attribute on DTAttribute {
  id
  locale
  version
  options {
    ... on DTAttColorImpl {
      id
      hexCode
    }
    ... on DTAttOptionImpl {
      id
    }
    value
  }
}
```
Result:
```
{
  "data": null
}
```

## Specifications

  - GraphQL for VSCode Extension Version:  0.3.18
  - VSCode Version: 1.62.3
  - OS Name: Windows
  - OS Version: 10.0.18363
  - graphql config filename and format example:

**Comment by acao** [comment]
is this when using the in-extension query execution? I think I know what could be the issue..

**Comment by pruss** [comment]
Yes.

**Comment by pruss** [comment]
0.3.21 breaks inline query execution?

**Comment by pruss** [comment]
With this  version the extension to be deactivated?

**Comment by acao** [comment]
huh that is strange, we have the extension activating all the time now using `*`

**Comment by acao** [comment]
added to the lsp here

https://github.com/graphql/graphiql/pull/2111
