### ISSUE TITLE
Query result does not display tags

### ISSUE THREAD

**Issue by pruss** [graphql/vscode-graphql#344]
## Actual Behavior
Tags within a string get converted to HTML instead of displaying plain with tags
<h3>Title</h3>

## Expected Behavior
\<h3\>Title\</h3\>

## Specifications

  - GraphQL for VSCode Extension Version:  0.3.18
  - VSCode Version: 1.62.3
  - OS Name: Windows
  - OS Version: 10.0.18363
  - graphql config filename and format example:

## Logs Of TS Server || GraphQL Language Service

**Comment by acao** [comment]
yikes! this is an xss issue, oops. we need to escape the tags at least

**Comment by acao** [comment]
this should address it!

https://github.com/graphql/vscode-graphql/pull/376
