### ISSUE TITLE
`vscode-graphql.restart` command not found

### ISSUE THREAD

**Issue by jeffsee55** [graphql/vscode-graphql#348]
## Actual Behavior
VSCode Manual restart prompts the error message: "vscode-graphql.restart" command not found.

Looks like there have been a few releases today, and I see a bug report in [another issue](https://github.com/graphql/vscode-graphql/issues/345) but this manifested as a separate message so wanted to post it here. Downgrading to the release from 3 months ago (0.3.18) fixes the issue

## Expected Behavior
Restart as expected

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.21 (and 0.3.20)
  - VSCode Version: 
  - OS Name: macOS Big Sur
  - OS Version: 11.5.2
  - graphql config filename and format example: https://github.com/tinacms/tinacms/blob/fa7a0419f8c6249130175154d40d0a9c3b61e1d1/graphql.config.yml

Admittedly a pretty complext GraphQL config file but doesn't seem related to that.

**Comment by acao** [comment]
I don't know why

**Comment by jeffsee55** [comment]
I did restart the editor a few times and installed/uninstalled, enabled/disabled but nothing seemed to work. I don't see anything in the Problems tab, is there something you want me to try to help diagnose?

**Comment by acao** [comment]
This has been resolved!
