### ISSUE TITLE
How do i disable "Execute Query"?

### ISSUE THREAD

**Issue by MariuzM** [graphql/vscode-graphql#378]
How do i disable this added line? 

![Screen Shot 2021-12-06 at 09 48 22](https://user-images.githubusercontent.com/36937039/144807562-6878b4c0-b865-4011-9acb-7c38315c0463.png)

**Comment by Tridie2000** [comment]
Add the following line to your `settings.json`-file:
`"vscode-graphql.showExecCodelens": false`

Restart or reload VS Code so the changes can take effect.
