### ISSUE TITLE
Syntax Error in .vue files

### ISSUE THREAD

**Issue by zigomir** [graphql/vscode-graphql#380]
## Actual Behavior

`Syntax Error: Cannot parse the unexpected character "<".GraphQL: Syntax` in `.vue` file

## Expected Behavior

No error

## Steps to Reproduce the Problem Or Description

Create new `.vue` file and paste `<template></template>` in it.

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.34
  - VSCode Version: 1.62.3
  - OS Name: macOS
  - OS Version: 12.0.1
  - graphql config filename and format example:

**Comment by zigomir** [comment]
Culprit being https://github.com/graphql/vscode-graphql/commit/f022958a60dc30aaeafe1b95fe0711965907a2fd

**Comment by acao** [comment]
my bad, I hadn't looked closely enough at this PR, it does not add a grammar for vue files as I had thought

**Comment by acao** [comment]
reverted in #387, 0.3.35 should be the fix version

**Comment by zigomir** [comment]
It's fixed now, but I'm really confused which version fixes it. I just tried installing latest `0.3.41` and event `0.3.34` and none of them have same problem 🤷‍♂️
