### ISSUE TITLE
GraphQL Configuration not pulling in JWT from environment. 

### ISSUE THREAD

**Issue by jstevens-level20** [graphql/vscode-graphql#424]
## Actual Behavior

When attempting to execute a query, I get the following response:

```json
{
  "errors": [
    {
      "message": "The supplied JWT is invalid or expired."
    }
  ]
}
```

When hard-coding in the JWT all works correctly.

## Expected Behavior

The JWT is pulled from the environment variable.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.41
  - VSCode Version: 1.64.0
  - OS Name: macOS
  - OS Version: Monterey (12.1)
  - graphql config filename and format example:

```javascript
// graphql.config.js
module.exports = {
  projects: {
    live: {
      schema: 'http://localhost:8020/graphql',
      extensions: {
        endpoints: {
          default: {
            url: 'http://localhost:8020/graphql',
            headers: {
              Authorization: `${process.env.GRAPHQL_API_TOKEN}`
            }
          }
        }
      }
    }
  }
};
```
  - .env config filename and format example:
```sh
# .env
GRAPHQL_API_TOKEN='...'
```

**Comment by lucagoslar** [comment]
Your issue might be similar to issue [#284](284).
@RKings [solved](284#issuecomment-983665679) it by requiring `dotenv` and pointing to the projects `.env` file.

```js
// graphql.config.js
require('dotenv').config({ path: __dirname + '/.env', });
```

**Comment by acao** [comment]
Thank you @lucagoslar !

**Comment by jstevens-level20** [comment]
Worked perfectly.  Thank you, @lucagoslar!!
