### ISSUE TITLE
Incorrect deployment to 0.3.50

### ISSUE THREAD

**Issue by Cellule** [graphql/vscode-graphql#451]
It seems https://github.com/graphql/vscode-graphql/pull/447 tried to deploy version 0.3.50
However that version was already pushed 2 months ago 
![image](https://user-images.githubusercontent.com/4157103/158086733-5ec55e93-3858-4422-a293-ff53456be9cd.png)

It seems the deployment pipeline should be triggered again for 0.3.51 (and figure out how 0.3.50 was deployed incorrectly in the first place)

Related #254

Creating a new issue hoping another maintainer can look into it since @acao is undergoing surgery at this time

**Comment by acao** [comment]
Ok, I think we're good now with `0.3.52`!

Still trying to figure out a strategy where we can pre-release on every merge, but this at least gets the pipeline working, and not with a stable release on every merge like before which is ideal. This will tide us over until we merge this repo with `graphiql`
