### ISSUE TITLE
Autocomplete does not work at all

### ISSUE THREAD

**Issue by incrypto32** [graphql/vscode-graphql#461]
## Actual Behavior
Autocompletion does not work at all
## Expected Behavior
When I start typing it should start auto-completing with valid types
## Specifications

  - GraphQL for VSCode Extension Version: v0.3.53
  - VSCode Version: 1.66.0
  - OS Name: macOS Monterey
  - OS Version: 12.2.1
  - graphql config filename and format example:

## Logs Of TS Server || GraphQL Language Service
The logs are empty

<img width="1512" alt="Screenshot 2022-04-05 at 7 39 25 PM" src="https://user-images.githubusercontent.com/44740264/161773212-3f54aeee-4501-4f95-88a4-9584020c5a8f.png">

**Comment by acao** [comment]
@incrypto32 just check the readme and you'll find it!
