### ISSUE TITLE
Validation failing for default value (custom directive) in SDL

### ISSUE THREAD

**Issue by xuo** [graphql/vscode-graphql#50]
![example265234](https://user-images.githubusercontent.com/6968409/42455653-23290c7e-8393-11e8-87da-5684f0d14070.png)

I am getting a validaiton error (`[GraphQL: Validation] Expected type String!, found false`) for my default value custom directive in my Prisma datamodel written in SDL. 
Seems like only detection of string values is supported?

**Comment by marktani** [comment]
It is also supposed to be a string. Try `@default(value: "false")`.

**Comment by xuo** [comment]
I see. Just kinda confusing since i started off with the react-fullstack-graphql boilerplate, where its not really demonstrated consistently (see [this](https://github.com/graphql-boilerplates/react-fullstack-graphql/blob/master/basic/server/database/datamodel.graphql) & [this](https://github.com/graphql-boilerplates/react-fullstack-graphql/blob/master/advanced/server/database/datamodel.graphql) file for example).
Also, in the [blog post about SDL](https://www.prisma.io/blog/graphql-sdl-schema-definition-language-6755bcb9ce51/) - you have an example: `likes: Int! @default(value: 0)` - getting the same validation error for `ID`, `Int ` & `Float ` values. (hence why i assumed that only string values are supported?)

**Comment by acao** [comment]
@xuo this is an error that comes from `graphql-js` `validate()` function and associated validation rules
