### ISSUE TITLE
Go To Definition No Longer works

### ISSUE THREAD

**Issue by tomitrescak** [graphql/vscode-graphql#63]
I am not sure if this is misconfiguration on my side, but Go To Definition No longer works for me. I tried on several projects on different computers and it is the case.

One repro is here: 

https://github.com/tomitrescak/corporator

Do you have some test project where it works? 
Thanks

[EDIT] I have just downloaded your project "graphql-server-example", No luck there. Is it maybe error in the latest visual studio code? I did not try to downgrade yet.

**Comment by tomitrescak** [comment]
Would you please confirm whether this is broken so I can maybe try to fix it, or is it problem of my configuration? Maybe some bad global dependencies?

**Comment by chanlito** [comment]
@tomitrescak mine isn't working either.

**Comment by tomitrescak** [comment]
@divyenduz you mention "Needs Reproduction", but I mentioned two repos where it does not work. You can just try the following one:

https://github.com/prisma/graphql-server-example

Thanks for looking into this. The plugin is otherwise spectacular!

**Comment by dontsave** [comment]
I'm running into the same issue with a Gatsby (graphql) project as well.

**Comment by divyenduz** [comment]
Thanks all for the feedback. Can any of you please share the logs for GraphQL Language Service? From your environment: https://github.com/prisma/vscode-graphql#a-testinglogging-graphql-language-features

**Comment by divyenduz** [comment]
@chanlito : It looks like you have the same fields on mutation type (maybe you are using schema stitching or something or maybe it is a multi-repo project - extension cannot tell if different files belong to different projects, if they have duplicates). 

This fails [`extendSchema` from `graphql-js`](https://github.com/graphql/graphql-js/blob/e83409712ef1493a7709a5754b0e72d1bd33c753/src/utilities/extendSchema.js#L108) being used by the [graphql-language-service](https://github.com/graphql/graphql-language-service/blob/master/packages/server/src/GraphQLCache.js#L638-L640).

Here is an example of how this might be going wrong: https://codesandbox.io/s/34lvxl4pn1

Posted this information here for anyone who might attempt a fix for this. This might require big changes in the language service.
