### ISSUE TITLE
Config setup to a .js-based schema?

### ISSUE THREAD

**Issue by jasonkylefrank** [graphql/vscode-graphql#64]
Hello!

GraphQL newbie here, trying to gain autocomplete and other goodies with this extension.  The issue I'm having is that my schema is a JavaScript file, thus a **`.js` extension**.  And I'm not sure if your system supports that kind of schema, since there are no examples which show that kind of schema file being used.

I have tried setting up a `.graphqlconfig.yml` file to enable auto-complete in my client-side `gql` queries, but it is not working - presumably because this plugin does not support connection to `.js`-based schemas?

### Here's what I tried for setting up my `.graphqlconfig.yml` file
At first I tried using the **GraphQL CLI**. But that failed since it would not let me specify my schema file which has a `.js` extension:  

![image](https://user-images.githubusercontent.com/7502365/44957375-b08f1400-ae9f-11e8-9b77-7489372ebb38.png)

Next I tried just **manually creating the `.graphqlconfig.yml` file**:

![image](https://user-images.githubusercontent.com/7502365/44957449-cea94400-aea0-11e8-8885-6eca2ea2855e.png)

### Results after my config setup
In my client-side `gql` queries, I tried pressing `control` + `spacebar` to get auto-complete possibilities which would relate to my schema, but it did not work:

![image](https://user-images.githubusercontent.com/7502365/44957457-eaace580-aea0-11e8-843a-53c72d877e2a.png)

### Summary
How can I use my `.js`-based schema file with this extension?

**Comment by ChiefORZ** [comment]
👍

**Comment by ChiefORZ** [comment]
https://github.com/prisma/graphql-config/blob/master/specification.md#configuring-a-schema-defined-programmatically

found this specification of `graphql-config`, but unfortunately this is not implemented yet

**Comment by acao** [comment]
@ChiefORZ your best bet nowadays is still to just write out the schema as a cache to SDL when mounting the schema. it's the most fast and performant way of evaluating schema for language tooling. this docs link is broken, but that approach should still work in graphql-config@3.0 as well.

**Comment by acao** [comment]
gonna close this, since js based schema SDL defintions are supported for schema completion now

**Comment by MariaSolOs** [comment]
I'm running into the same problem!
