### ISSUE TITLE
Validation gets stuck and it has no intellisense

### ISSUE THREAD

**Issue by herkulano** [graphql/vscode-graphql#70]
Trying https://github.com/prisma/graphql-prisma-typescript as is I keep getting this message in the output:
```
(node:36522) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: Field Subscription.city can only be defined once.
```

I also don't get any intellisense or autocompletion and the validation gets stuck, meaning, if I type an error and correct it the error stays highlighted.

**Comment by divyenduz** [comment]
Duplicate (or subset) of https://github.com/prisma/vscode-graphql/issues/72
