### ISSUE TITLE
Support for markdown code blocks syntax highlighting

### ISSUE THREAD

**Issue by MichalLytek** [graphql/vscode-graphql#78]
It would be nice if `vscode-graphql` supports syntax highlighting in markdown's code blocks, just like the competitive extension does:
https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode

## Expected Behavior

![image](https://user-images.githubusercontent.com/10618781/47170098-7f5e8c00-d305-11e8-9086-d0f237df66b2.png)

## Actual Behavior
No syntax highlighting in markdown's code blocks.

## Steps to Reproduce the Problem Or Description
Just write a *.md file with code block like on SS above.

## Specifications

  - VSCode Version: 1.28.2
  - OS Name: Windows 10
  - OS Version: 17134

## Logs Of TS Server || GraphQL Language Service
N/A

**Comment by 19majkel94** [comment]
I think that VSCode delegates the highlighting to the extension that have registered support of this language:
https://code.visualstudio.com/docs/extensionAPI/language-support#_syntax-highlighting

So it looks like you would need to have two extensions for GraphQL installed parallel to clash 😕

**Comment by ghuser** [comment]
Maybe check the solution provided in the [fwcd kotlin extension](https://github.com/fwcd/vscode-kotlin-ide/blob/0.2.11/package.json#L52) which is using `injectTo:["text.html.markdown"]` in `package.json`

Doc ref: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#creating-a-basic-injection-grammar

**Comment by bitjson** [comment]
Thanks @ghuser, I just made a PR to add support 👍 https://github.com/graphql/vscode-graphql/pull/243

**Comment by vwkd** [comment]
Would be nice if highlighting would also work in the Markdown Preview, which the above mentioned competitive extension does not support.
